var backgrounds = [
  {"text":"Modern Condo",
   "imageSrc":"./images/bgThumb/01-moderncondo.jpg",
   "fullUrl":"./images/bgFull/01-moderncondo.jpg"},
  {"text":"Hallway",
   "imageSrc":"./images/bgThumb/02-hallway.jpg",
   "fullUrl":"./images/bgFull/02-hallway.jpg"},
  {"text":"Dock",
   "imageSrc":"./images/bgThumb/03-dock.jpg",
   "fullUrl":"./images/bgFull/03-dock.jpg"},
  {"text":"Rock Coast",
   "imageSrc":"./images/bgThumb/04-rockcoast.jpg",
   "fullUrl":"./images/bgFull/04-rockcoast.jpg"},
  {"text":"Traditional Kitchen",
   "imageSrc":"./images/bgThumb/05-tradkitchen.jpg",
   "fullUrl":"./images/bgFull/05-tradkitchen.jpg"},
  {"text":"Suburb",
   "imageSrc":"./images/bgThumb/06-suburb.jpg",
   "fullUrl":"./images/bgFull/06-suburb.jpg"},
  {"text":"White Room",
   "imageSrc":"./images/bgThumb/07-whiteroom.jpg",
   "fullUrl":"./images/bgFull/07-whiteroom.jpg"},
  {"text":"Poolside",
   "imageSrc":"./images/bgThumb/08-poolside.jpg",
   "fullUrl":"./images/bgFull/08-poolside.jpg"},
  {"text":"Mountain Range",
   "imageSrc":"./images/bgThumb/09-mountainrange.jpg",
   "fullUrl":"./images/bgFull/09-mountainrange.jpg"},
  {"text":"Apartments",
   "imageSrc":"./images/bgThumb/10-apartments.jpg",
   "fullUrl":"./images/bgFull/10-apartments.jpg"},
  {"text":"Condo Kitchen",
   "imageSrc":"./images/bgThumb/11-condokitchen.jpg",
   "fullUrl":"./images/bgFull/11-condokitchen.jpg"},
  {"text":"California Coast",
   "imageSrc":"./images/bgThumb/12-calicoast.jpg",
   "fullUrl":"./images/bgFull/12-calicoast.jpg"},
  {"text":"Hill Cottage",
   "imageSrc":"./images/bgThumb/13-hillcottage.jpg",
   "fullUrl":"./images/bgFull/13-hillcottage.jpg"},
  {"text":"Desert Home",
   "imageSrc":"./images/bgThumb/14-deserthome.jpg",
   "fullUrl":"./images/bgFull/14-deserthome.jpg"},
  {"text":"Modern Kitchen",
   "imageSrc":"./images/bgThumb/15-modkitchen.jpg",
   "fullUrl":"./images/bgFull/15-modkitchen.jpg"},
  {"text":"Modern Kitchen 2",
   "imageSrc":"./images/bgThumb/16-modkitchen.jpg",
   "fullUrl":"./images/bgFull/16-modkitchen.jpg"},
  {"text":"Apartment Garden",
   "imageSrc":"./images/bgThumb/17-apartmentgarden.jpg",
   "fullUrl":"./images/bgFull/17-apartmentgarden.jpg"},
  {"text":"Palms",
   "imageSrc":"./images/bgThumb/18-palms.jpg",
   "fullUrl":"./images/bgFull/18-palms.jpg"},
  {"text":"Sunset Beach",
   "imageSrc":"./images/bgThumb/19-sunsetbeach.jpg",
   "fullUrl":"./images/bgFull/19-sunsetbeach.jpg"},
  {"text":"Lighthouse 2",
   "imageSrc":"./images/bgThumb/20-lighthouse.jpg",
   "fullUrl":"./images/bgFull/20-lighthouse.jpg"},
  {"text":"Sunset Coast",
   "imageSrc":"./images/bgThumb/21-sunsetcoast.jpg",
   "fullUrl":"./images/bgFull/21-sunsetcoast.jpg"},
  {"text":"Living Room",
   "imageSrc":"./images/bgThumb/22-livingroom.jpg",
   "fullUrl":"./images/bgFull/22-livingroom.jpg"},
  {"text":"Lake",
   "imageSrc":"./images/bgThumb/23-lake.jpg",
   "fullUrl":"./images/bgFull/23-lake.jpg"},
  {"text":"Sailboat",
   "imageSrc":"./images/bgThumb/24-sailboat.jpg",
   "fullUrl":"./images/bgFull/24-sailboat.jpg"},
  {"text":"Mountain Lake",
   "imageSrc":"./images/bgThumb/25-mountainlake.jpg",
   "fullUrl":"./images/bgFull/25-mountainlake.jpg"},
  {"text":"Purple Palms",
   "imageSrc":"./images/bgThumb/26-purplepalm.jpg",
   "fullUrl":"./images/bgFull/26-purplepalm.jpg"},
  {"text":"White Couch",
   "imageSrc":"./images/bgThumb/27-whitecouch.jpg",
   "fullUrl":"./images/bgFull/27-whitecouch.jpg"},
  {"text":"Street",
   "imageSrc":"./images/bgThumb/28-street.jpg",
   "fullUrl":"./images/bgFull/28-street.jpg"},
  {"text":"Tan Couch",
   "imageSrc":"./images/bgThumb/29-tancouch.jpg",
   "fullUrl":"./images/bgFull/29-tancouch.jpg"},
  {"text":"Fancy Room",
   "imageSrc":"./images/bgThumb/30-fancyroom.jpg",
   "fullUrl":"./images/bgFull/30-fancyroom.jpg"},
  {"text":"Modern Room",
   "imageSrc":"./images/bgThumb/31-modroom.jpg",
   "fullUrl":"./images/bgFull/31-modroom.jpg"},
  {"text":"Townhouse",
   "imageSrc":"./images/bgThumb/32-townhouse.jpg",
   "fullUrl":"./images/bgFull/32-townhouse.jpg"},
  {"text":"Dock Chairs",
   "imageSrc":"./images/bgThumb/33-chairdock.jpg",
   "fullUrl":"./images/bgFull/33-chairdock.jpg"},
  {"text":"Roman",
   "imageSrc":"./images/bgThumb/34-roman.jpg",
   "fullUrl":"./images/bgFull/34-roman.jpg"},
  {"text":"Lake Chairs",
   "imageSrc":"./images/bgThumb/35-chairlake.jpg",
   "fullUrl":"./images/bgFull/35-chairlake.jpg"},
  {"text":"Black Couch",
   "imageSrc":"./images/bgThumb/36-blackcouch.jpg",
   "fullUrl":"./images/bgFull/36-blackcouch.jpg"},
  {"text":"Suburb 2",
   "imageSrc":"./images/bgThumb/37-suburb.jpg",
   "fullUrl":"./images/bgFull/37-suburb.jpg"},
  {"text":"White House",
   "imageSrc":"./images/bgThumb/38-whitehouse.jpg",
   "fullUrl":"./images/bgFull/38-whitehouse.jpg"},
  {"text":"White Living Room",
   "imageSrc":"./images/bgThumb/39-whitelivingroom.jpg",
   "fullUrl":"./images/bgFull/39-whitelivingroom.jpg"},
  {"text":"San Fran",
   "imageSrc":"./images/bgThumb/40-sanfran.jpg",
   "fullUrl":"./images/bgFull/40-sanfran.jpg"},
  {"text":"Sectional",
   "imageSrc":"./images/bgThumb/41-sectional.jpg",
   "fullUrl":"./images/bgFull/41-sectional.jpg"},
  {"text":"White Sectional",
   "imageSrc":"./images/bgThumb/42-whitesectional.jpg",
   "fullUrl":"./images/bgFull/42-whitesectional.jpg"},
  {"text":"Exterior",
   "imageSrc":"./images/bgThumb/43-exterior.jpg",
   "fullUrl":"./images/bgFull/43-exterior.jpg"},
];
var colorSchemes = [
  {"text":"Eggplant",
   "imageSrc":"./images/color01.jpg",
   "color1":"#639c2b",
   "color2":"#342f45",
   "color3":"#6b638c"},
  {"text":"Blue and Tan",
   "imageSrc":"./images/color02.jpg",
   "color1":"#339cb2",
   "color2":"#48433d",
   "color3":"#967f60"},
  {"text":"Entertainment District",
   "imageSrc":"./images/color03.jpg",
   "color1":"#c13341",
   "color2":"#3a3732",
   "color3":"#706a5e"},
  {"text":"Green Oak",
   "imageSrc":"./images/color04.jpg",
   "color1":"#9f8264",
   "color2":"#2f3917",
   "color3":"#9c7f5f"},
  {"text":"Ocean Sky",
   "imageSrc":"./images/color05.jpg",
   "color1":"#4489a8",
   "color2":"#0e2c46",
   "color3":"#73b1ca"},
  {"text":"Sunburst",
   "imageSrc":"./images/color06.jpg",
   "color1":"#cc5207",
   "color2":"#342a20",
   "color3":"#876c4e"},
  {"text":"Harrison",
   "imageSrc":"./images/ipre.jpg",
   "color1":"#569779",
   "color2":"#1f4335",
   "color3":"#57967b"},
  {"text":"Fisher",
   "imageSrc":"./images/macrealty.jpg",
   "color1":"#9cd3ab",
   "color2":"#163041",
   "color3":"#285678"},
  {"text":"Hamill",
   "imageSrc":"./images/rightathome.jpg",
   "color1":"#e7b242",
   "color2":"#470d59",
   "color3":"#9165a0"},
  {"text":"Quinn",
   "imageSrc":"./images/tarbell.jpg",
   "color1":"#c12030",
   "color2":"#272727",
   "color3":"#c61f33"},
];